server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopsneaker3?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locate: en
  google:
    ai:
      project-id: thermal-micron-435515-i8 # Replace with your Google Cloud project ID
      location: us-central1
      model: gemini-2.0-flash-001
  autoconfigure:
    exclude:
      - org.springframework.ai.autoconfigure.vectorstore.chroma.ChromaVectorStoreAutoConfiguration
api:
  prefix: api/v1
jwt:
  expiration: 2592000
  secretKey: U0roD0fdqXHh6yEzmYciXkhmHlFsS7v2Xa3bLVPsyLQ=

logging.level.org.springframework.security: DEBUG

# Chroma Vector Database Configuration
chroma:
  collection:
    name: sneakers-collection
  base:
    url: ${CHROMA_BASE_URL:http://localhost:8000}

# AI Features Configuration
ai:
  enabled: true # Set to true when Google Cloud is configured

# VNPay Configuration
vnpay:
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:4200/vnpay-return
  tmn-code: JEQ64ZP9
  secret-key: K2MEKYRFARPM7ELWJSJ2UBZME3LSUYN6
  api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
  version: 2.1.0
